apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server
    lang: python
  namespace: default
spec:
  containers:
    - image: python
      name: http-server
      command: ["python", "-m", "http.server", "8000"]
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
